name: pipeline t4

on:
  push:
    branches: [ "feature/devsecops-t4" ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: gitclone
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache de Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Cache de SonarQube
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar    
      - name: Compilar el proyecto con mvn
        run: mvn -B clean package -DskipTests

      - name: ojala funque sonarcloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=villarwch_pet-clinic \
            -Dsonar.qualitygate.wait=true
