name: pipeline t4

on:
  push:
    branches: [ "feature/devsecops-t4" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: gitclone
        uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache de Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Cache de SonarQube
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: |
            ${{ runner.os }}-sonar    
      - name: Compilar el proyecto con mvn
        run: mvn -B clean package -DskipTests

      - name: ojala funque sonarcloud
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=villarwch_pet-clinic \
            -Dsonar.qualitygate.wait=true

      - name: SCA DC
        continue-on-error: true
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn org.owasp:dependency-check-maven:12.2.2:check \
            -DfailBuildOnCVSS=4 \
            -DnvdApiKey=${NVD_API_KEY} \
            -DassemblyAnalyzerEnabled=false

      - name: Subir reporte
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html

      - name: Construir imagen Docker
        run: docker build -t pet-clinic:${{ github.sha }} .

      - name: Image Security con Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: pet-clinic:${{ github.sha }}
          format: table
          severity: CRITICAL,HIGH,MEDIUM
          exit-code: '1'